from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from reportlab.lib.colors import HexColor
from io import BytesIO
from datetime import datetime
from typing import List, Dict

def create_pdf_chat_history(chat_history: List[Dict], filename: str = "chat_history.pdf") -> BytesIO:
    """
    Generate a beautifully formatted PDF from chat history.
    
    Args:
        chat_history: List of dicts with 'question', 'answer', and 'sources' keys
        filename: Name of the PDF file
        
    Returns:
        BytesIO buffer containing the PDF
    """
    buffer = BytesIO()
    
    # Create PDF document
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.75*inch,
        leftMargin=0.75*inch,
        topMargin=1*inch,
        bottomMargin=0.75*inch
    )
    
    # Container for PDF elements
    story = []
    
    # Define custom styles
    styles = getSampleStyleSheet()
    
    # Title style
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=HexColor('#6366f1'),
        spaceAfter=30,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )
    
    # Subtitle style
    subtitle_style = ParagraphStyle(
        'CustomSubtitle',
        parent=styles['Normal'],
        fontSize=12,
        textColor=HexColor('#6b7280'),
        spaceAfter=20,
        alignment=TA_CENTER,
        fontName='Helvetica'
    )
    
    # Question style
    question_style = ParagraphStyle(
        'Question',
        parent=styles['Normal'],
        fontSize=12,
        textColor=HexColor('#1f2937'),
        spaceAfter=10,
        leftIndent=0,
        fontName='Helvetica-Bold',
        backColor=HexColor('#f3f4f6'),
        borderPadding=10,
        borderWidth=1,
        borderColor=HexColor('#e5e7eb')
    )
    
    # Answer style
    answer_style = ParagraphStyle(
        'Answer',
        parent=styles['Normal'],
        fontSize=11,
        textColor=HexColor('#374151'),
        spaceAfter=20,
        leftIndent=20,
        fontName='Helvetica',
        leading=16
    )
    
    # Source style
    source_style = ParagraphStyle(
        'Source',
        parent=styles['Normal'],
        fontSize=9,
        textColor=HexColor('#6b7280'),
        spaceAfter=10,
        leftIndent=30,
        fontName='Helvetica-Oblique',
        backColor=HexColor('#fefce8'),
        borderPadding=8
    )
    
    # Add title
    story.append(Paragraph("📚 Chat with Your Notes", title_style))
    
    # Add subtitle with date
    current_date = datetime.now().strftime("%B %d, %Y at %I:%M %p")
    story.append(Paragraph(f"Conversation Export | {current_date}", subtitle_style))
    
    # Add separator
    story.append(Spacer(1, 0.3*inch))
    
    # Add each Q&A pair
    for i, chat in enumerate(chat_history, 1):
        # Question number header
        question_header = f"<b>Question {i}:</b> {chat['question']}"
        story.append(Paragraph(question_header, question_style))
        story.append(Spacer(1, 0.1*inch))
        
        # Answer
        answer_text = f"<b>Answer:</b><br/>{chat['answer']}"
        story.append(Paragraph(answer_text, answer_style))
        story.append(Spacer(1, 0.15*inch))
        
        # Sources (optional - show first 2 sources)
        if 'sources' in chat and len(chat['sources']) > 0:
            story.append(Paragraph("<b>📚 Sources:</b>", source_style))
            for j, (chunk, score) in enumerate(chat['sources'][:2], 1):
                # Clean and truncate chunk
                clean_chunk = " ".join(chunk.split())
                truncated_chunk = clean_chunk[:200] + "..." if len(clean_chunk) > 200 else clean_chunk
                source_text = f"<i>Source {j} (Similarity: {score:.4f}):</i><br/>{truncated_chunk}"
                story.append(Paragraph(source_text, source_style))
                story.append(Spacer(1, 0.05*inch))
        
        # Add spacing between Q&A pairs
        story.append(Spacer(1, 0.3*inch))
        
        # Add page break after every 3 Q&A pairs to avoid crowding
        if i % 3 == 0 and i < len(chat_history):
            story.append(PageBreak())
    
    # Add footer on last page
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=9,
        textColor=HexColor('#9ca3af'),
        alignment=TA_CENTER,
        fontName='Helvetica-Oblique'
    )
    story.append(Spacer(1, 0.5*inch))
    story.append(Paragraph(
        "Generated by Chat with Your Notes | Powered by Groq AI & FAISS",
        footer_style
    ))
    
    # Build PDF
    doc.build(story)
    
    # Reset buffer position
    buffer.seek(0)
    return buffer